<script setup lang="ts">
import CodeCompare from '../components/CodeCompare.vue'
</script>

<template>
  <div class="space-y-5">
    <div class="pb-5 border-b border-white/[0.06] mb-2">
      <h2 class="text-xl font-bold text-white tracking-tight">数据类型对比</h2>
      <p class="text-sm text-zinc-400 mt-1.5">MySQL 与 PostgreSQL 常用数据类型的映射关系</p>
    </div>

    <CodeCompare
      title="整数类型"
      description="TINYINT/SMALLINT/INT/BIGINT 映射"
      mysql="TINYINT       -- 1字节 (-128 ~ 127)
SMALLINT      -- 2字节
INT / INTEGER -- 4字节
BIGINT        -- 8字节"
      postgresql="SMALLINT      -- 2字节
SMALLINT      -- 2字节
INTEGER       -- 4字节
BIGINT        -- 8字节
-- 注意: PostgreSQL 没有 TINYINT
-- 可用 SMALLINT 或自定义 domain 替代"
    />

    <CodeCompare
      title="字符串类型"
      description="VARCHAR / TEXT / CHAR 的差异"
      mysql="VARCHAR(255)  -- 变长字符串
TEXT          -- 长文本 (最大 64KB)
MEDIUMTEXT    -- 中等文本 (最大 16MB)
LONGTEXT      -- 长文本 (最大 4GB)
CHAR(10)      -- 定长字符串"
      postgresql="VARCHAR(255)  -- 变长字符串
TEXT          -- 无限长度文本
TEXT          -- 无限长度文本
TEXT          -- 无限长度文本
CHAR(10)      -- 定长字符串
-- 注意: PostgreSQL 中 TEXT 无长度限制"
    />

    <CodeCompare
      title="布尔类型"
      mysql="TINYINT(1)    -- 0 = false, 1 = true
BOOLEAN       -- TINYINT(1) 的别名"
      postgresql="BOOLEAN       -- true / false
BOOL          -- BOOLEAN 的别名
-- 可以用 1/0, 't'/'f', 'true'/'false'"
    />

    <CodeCompare
      title="自增主键"
      mysql="id INT AUTO_INCREMENT PRIMARY KEY
-- 或
id INT PRIMARY KEY AUTO_INCREMENT"
      postgresql="id SERIAL PRIMARY KEY
-- SERIAL = INTEGER + SEQUENCE

-- 或更明确的写法:
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY

-- 或:
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    />

    <CodeCompare
      title="枚举类型"
      mysql="CREATE TABLE users (
  status ENUM('active', 'inactive', 'banned')
);"
      postgresql="CREATE TABLE users (
  status VARCHAR(20) CHECK (
    status IN ('active', 'inactive', 'banned')
  )
);

-- 或使用自定义 TYPE:
CREATE TYPE user_status AS ENUM (
  'active', 'inactive', 'banned'
);
CREATE TABLE users (
  status user_status
);"
    />
  </div>
</template>
